root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api.exe ./cmd/api"
bin = "tmp/api.exe"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
kill_delay = "2s" 
rerun = false

[misc]
  clean_on_exit = true 

[log]
time = true